### ISSUE TITLE
 安装异常

### ISSUE THREAD

**Issue by ASTARCHEN** [taojy123/nanorm#2]
python版本3.5，win10 os。
报错缺thread包。
我以为是threading包，修改源码之后依然无法安装。
另建议增加requirements.txt文件。
期待回复。

**Comment by taojy123** [comment]
多线程用到了 thread 这个库。
 thread 和 threading 在 python2 中是两个不同的库，而 python3 只有threading 没有 thread。

目前这个 nanorm 只支持 python2，我会考虑兼容 python3 的，还有你提的增加 requirements 的意见也非常好。

**Comment by ASTARCHEN** [comment]
3Q

**Comment by taojy123** [comment]
哥们，我这个默默无名的项目，你是怎么发现的

**Comment by ASTARCHEN** [comment]
在pypi上查看发布的新包的时候看你发了个新包，然后就发现的。
看你最近才发布工具，所以觉得你应该会很快发现issue然后回复的，嘿嘿。
